config/routes.rb
Rails.application.routes.draw do
  resources :blogs do
    resources :entries, only: [:create, :destroy, :edit, :new, :show, :update] do
      resources :comments, only: [:create, :destroy] do
        put :approve
      end
    end
  end
  root 'blogs#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_many :entries, dependent: :destroy
  validates :title, presence: true
  delegate :new, :present?,:find, to: :entries, prefix: true
  delegate :any?, :count, :full_messages, to: :errors, prefix: true

  def index
    Blog.all
  end
end

app/models/blogs_presenter.rb
class BlogsPresenter
  attr_accessor :blog

  def initialize(args)
    @params = args[:params]
    set_path_models
  end

  def blog_new(blog_params)
    @blog = Blog.new(blog_params)
  end

  private

  def set_path_models
    @blog = find_path_blog
  end

  def find_path_blog
    return Blog.where("id = #{@params[:id]}").first if @params[:id]
    Blog.new
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :entry
  enum status: {unapproved: 1, approved: 2}
  validates :body, presence: true
  delegate :full_messages, :any?, :count, to: :errors, prefix: true

  scope :where_persisted, -> {
    where.not(id: nil)
  }
end

app/models/comments_presenter.rb
class CommentsPresenter
  attr_reader :blog, :entry
  attr_accessor :comment

  def initialize(args)
    @params = args[:params]
    set_path_models
  end

  private

  def set_path_models
    @blog = Blog.find(@params[:blog_id])
    @entry = blog.entries_find(@params[:entry_id])
    @comment = find_path_comment
  end

  def find_path_comment
    return entry.comments_find(@params[:comment_id]) if @params[:comment_id]
    return entry.comments_find(@params[:id]) if @params[:id]
    Comment.new
  end
end

app/models/entries_presenter.rb
class EntriesPresenter
  attr_reader :blog, :comment
  attr_accessor :entry

  def initialize(args)
    @params = args[:params]
    set_path_models
  end

  def blog_entries_new(entry_params)
    @entry = blog_entries.new(entry_params)
  end

  private

  def set_path_models
    @blog = Blog.find(@params[:blog_id])
    @entry = find_path_entry
    @comment = Comment.new
  end

  def find_path_entry
    return blog.entries_find(@params[:id]) if @params[:id]
    Entry.new
  end
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :blog
  has_many :comments, dependent: :destroy
  validates :title, presence: true
  delegate :full_messages, :any?, :count, to: :errors, prefix: true
  delegate :find, :new, :where_persisted, to: :comments, prefix: true
  delegate :present?, to: :comments_where_persisted, prefix: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  attr_reader :presenter
  before_action :set_presenter
  delegate :blog, to: :presenter, prefix: true

  def create
    presenter.blog = Blog.new(blog_params)
    render :new and return unless presenter_blog.save
    redirect_to presenter_blog, notice: 'Blog was successfully created.'
  end

  def update
    render :edit and return unless presenter_blog.update(blog_params)
    redirect_to presenter_blog, notice: 'Blog was successfully updated.'
  end

  def destroy
    presenter_blog.destroy!
    redirect_to blogs_url, notice: 'Blog was successfully destroyed.'
  end

  private

  def set_presenter
    @presenter = BlogsPresenter.new(params: params)
  end

  def blog_params
    params.require(:blog).permit(:title)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_presenter
  attr_reader :presenter
  delegate :blog, :entry, :comment, to: :presenter, prefix: true

  def approve
    presenter_comment.approved!
    redirect_to blog_entry_path(presenter_blog, presenter_entry), notice: 'Comment was successfully approved.'
  end

  def create
    presenter.comment = presenter_entry.comments_new(comment_params)
    unless presenter_comment.save
      render template: 'entries/show' and return
    end

    redirect_to blog_entry_path(presenter_blog, presenter_entry), notice: 'Comment was successfully created.'
  end

  def destroy
    presenter_comment.destroy!
    redirect_to blog_entry_path(presenter_blog, presenter_entry), notice: 'Comment was successfully destroyed.'
  end

  private

  def set_presenter
    @presenter = CommentsPresenter.new(params: params)
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_presenter
  attr_reader :presenter
  delegate :blog, :entry, to: :presenter, prefix: true

  def create
    presenter.entry = presenter_blog.entries_new(entry_params)
    render :new and return unless presenter_entry.save
    redirect_to blog_entry_path(presenter_blog, presenter_entry), notice: 'Entry was successfully created.'
  end

  def update
    return render :edit unless presenter_entry.update(entry_params)
    redirect_to blog_entry_path(presenter_blog, presenter_entry), notice: 'Entry was successfully updated.'
  end

  def destroy
    presenter_entry.destroy!
    redirect_to presenter_blog, notice: 'Entry was successfully destroyed.'
  end

  private

  def set_presenter
    @presenter = EntriesPresenter.new(params: params)
  end

  def entry_params
    params.require(:entry).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/blogs/_form.html.haml
= form_for blog do |f|
  - if blog.errors_any?
    #error_explanation
      %h2= "#{pluralize(blog.errors_count, "error")} prohibited this blog from being saved:"
      %ul
        - blog.errors_full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title
  .actions
    = f.submit 'Save'

app/views/blogs/_index.html.haml
%table.table-blogs
  %thead
    %tr
      %th Title
      %th &nbsp;
      %th &nbsp;
      %th &nbsp;
  %tbody
    - blog.index.each do |blog|
      %tr
        %td= blog.title.html_safe
        %td= link_to 'Show', blog
        %td= link_to 'Edit', edit_blog_path(blog)
        %td= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' }

app/views/blogs/_show.html.haml
%h1
  Blog title:
  = blog.title

app/views/blogs/edit.html.haml
%h1 Editing blog

= render 'form', blog: @presenter.blog

%ul.controls
  %li= link_to 'Show', @presenter.blog
  %li= link_to 'Back', blogs_path

app/views/blogs/index.html.haml
%h1 Listing blogs

= render 'blogs/index', blog: @presenter.blog

%ul.controls
  %li= link_to 'New Blog', new_blog_path

app/views/blogs/new.html.haml
%h1 New blog

= render 'form', blog: @presenter.blog

%ul.controls
  %li= link_to 'Back', blogs_path

app/views/blogs/show.html.haml
- if notice
  %p#notice= notice

= render 'blogs/show', {blog: @presenter.blog}

%ul.controls
  %li= link_to 'Edit', edit_blog_path(@presenter.blog)
  %li= link_to 'Back', blogs_path

%h2 Listing entries

= render 'entries/index', {blog: @presenter.blog}



%ul.controls
  %li= link_to 'New Entry', new_blog_entry_path(@presenter.blog)

app/views/comments/_form.html.haml
= form_for [blog,entry,comment] do |f|
  - if comment.errors_any?
    #error_explanation
      %h2= "#{pluralize(comment.errors_count, "error")} prohibited this comment from being saved:"
      %ul
        - comment.errors_full_messages.each do |message|
          %li= message

  .field
    = f.label :body
    = f.text_area :body
  .actions
    = f.submit 'Save'

app/views/comments/_index.html.haml
- if entry.comments_where_persisted_present?
  %table
    %thead
      %tr
        %th Body
        %th &nbsp;
        %th &nbsp;
    %tbody
      - entry.comments_where_persisted.each do |comment|
        %tr
          %td
            - if comment.approved?
              = comment.body
            - else
              unapproved
          %td
            - if  comment.unapproved?
              = link_to 'Approve', blog_entry_comment_approve_path(blog, entry, comment), method: :put
          %td= link_to 'Destroy', blog_entry_comment_path(blog, entry, comment), method: :delete, data: {confirm: 'are you sure?'}

app/views/entries/_form.html.haml
= form_for [blog, entry] do |f|
  - if entry.errors_any?
    #error_explanation
      %h2= "#{pluralize(entry.errors_count, "error")} prohibited this entry from being saved:"
      %ul
        - entry.errors_full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body
  .actions
    = f.submit 'Save'

app/views/entries/_index.html.haml
- if blog.entries_present?
  %table.table-entries
    %thead
      %tr
        %th Title
        %th Body
        %th &nbsp;
        %th &nbsp;
        %th &nbsp;
    %tbody
      - blog.entries.each do |entry|
        %tr
          %td= entry.title
          %td= entry.body
          %td= link_to 'Show', blog_entry_path(blog, entry)
          %td= link_to 'Edit', edit_blog_entry_path(blog, entry)
          %td= link_to 'Destroy', blog_entry_path(blog, entry), method: :delete, data: {confirm: 'are you sure?'}

app/views/entries/_show.html.haml
%p
  %strong Blog Title:
  = blog.title
%p
  %strong Title:
  = entry.title
%p
  %strong Body:
  = entry.body

app/views/entries/edit.html.haml
%h1 Editing entry

= render 'form', blog: @presenter.blog, entry: @presenter.entry

%ul.controls
  %li= link_to 'Show', [@presenter.blog,@presenter.entry]
  %li= link_to 'Back', @presenter.blog

app/views/entries/new.html.haml
%h1 New entry

= render 'form', blog: @presenter.blog, entry: @presenter.entry

%ul.controls
  %li= link_to 'Back', @presenter.blog

app/views/entries/show.html.haml
- if notice
  %p#notice= notice

%h1 Entry show

= render 'entries/show', {blog: @presenter.blog,entry: @presenter.entry}

%ul.controls
  %li= link_to 'Edit', edit_blog_entry_path(@presenter.blog,@presenter.entry)
  %li= link_to 'Back', @presenter.blog

= render 'comments/index', {blog: @presenter.blog,entry: @presenter.entry}

%h2 New Comment
= render 'comments/form', {blog: @presenter.blog,entry: @presenter.entry,comment: @presenter.comment}

app/views/layouts/application.html.haml
!!!
%html{lang: "ja"}
  %head
    %title RailsAssignmentCrudNest
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    #wrapper
      = yield